### ISSUE TITLE
Format the validation response

### ISSUE THREAD

**Issue by devlegacy** [whefter/nestjs-joi#12]
Is there a way to trap errors and generate a custom response?

https://github.com/whefter/nestjs-joi/blob/master/src/internal/joi.pipe.ts#L142

**Comment by whefter** [comment]
NestJS provides exception filters (https://docs.nestjs.com/exception-filters) to handle errors thrown in controllers, such as errors thrown by pipes.

Closing, feel free to reopen if you encounter an issue related to the error handling in the JoiPipe itself.

**Comment by devlegacy** [comment]
Yes, I catched the error, but the throw return a string and not Joi Error Object

- throw new JoiPipeValidationException(message);

- https://github.com/whefter/nestjs-joi/blob/e6a404cfaecd28238357aeff13015ad1fbe72145/src/internal/joi.pipe.ts#L150

**Comment by whefter** [comment]
I see what you mean, it looks like this is a separate issue: https://github.com/whefter/nestjs-joi/issues/13
