### ISSUE TITLE
Add formatError option to pipeOpts

### ISSUE THREAD

**Issue by rachaelhouse** [whefter/nestjs-joi#13]
## Description
We would like to a boolean new field to pipeOpts (`JoiPipeOptions` interface) that when enabled would pass through the error message instead of formatting the error message. 
Specifically before [this line](https://github.com/whefter/nestjs-joi/blob/e6a404cfaecd28238357aeff13015ad1fbe72145/src/internal/joi.pipe.ts#L145) we would add a check for the new field and if present return the message as `error. details` instead of the formatted message.

**Comment by rachaelhouse** [comment]
@whefter happy to contribute this change if you agree with what I have outlined above.

**Comment by whefter** [comment]
Sounds good! The field should have a default value of `false` to ensure backwards compatibility. Thanks for this.
