### ISSUE TITLE
How can i define 'or' when working with DTO object 

### ISSUE THREAD

**Issue by liorzmetis** [whefter/nestjs-joi#18]
I would like to define 'or' when using DTO classes 

<img width="348" alt="image" src="https://user-images.githubusercontent.com/95632109/177323996-26311af3-6913-409d-be51-609ae96bb010.png">

vs 

<img width="437" alt="image" src="https://user-images.githubusercontent.com/95632109/177323841-88b59fbd-f9bd-44be-9db5-f40a6312fece.png">

**Comment by whefter** [comment]
Thank you, that appears to be something that is not easily done yet. One possible implementation would be to add a customizer function argument to `@JoiSchemaOption()`, similar to the way it works on `@JoiSchema()`. That function would allow arbitrary customizations of the constructed object schema.

e.g.
```typescript
@JoiSchemaOptions({}, (schema) => schema.or('prop1', 'prop2')
```

Would that cover your case?

**Comment by whefter** [comment]
Another way to do it would be a separate decorator, e.g.

```typescript
@JoiSchemaCustomizer((schema) => schema.or('prop1', 'prop2'))
```

That would avoid mixing different concerns. I am leaning towards that one.

**Comment by whefter** [comment]
Added in new v1.8.0.
