### ISSUE TITLE
JoiSchemaCustomization is missing in index.d.ts file

### ISSUE THREAD

**Issue by marmotz** [whefter/nestjs-joi#21]
Could you please fix it to use this decorator in Typescript projects ?

Thank you

**Comment by rlittolff-onatera** [comment]
Thank you !

**Comment by whefter** [comment]
Released, v1.8.2. Should be available in a couple of minutes.
Note that it is also possible to use the `JoiSchemaCustomization` exported from `joi-class-decorators`, this package just re-exports it for convenience.

**Comment by marmotz** [comment]
Yes that's what I did in the meantime but it was a little weird to have this decorator imported in a different way
