### ISSUE TITLE
Custom validation error handler.

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [whefter/nestjs-joi#3]
Hi, thanks for this package. I am trying to validate using the code below.

`public async login(@Body(new JoiPipe({ group: 'TEST' })) loginRequest: LoginRequest): Promise<AuthResponse> {
        console.log('Request validated');
}`

The validation fails when proper input is not given, but I am not able to send a custom error code. It is throwing a default 400 BAD REQUEST error but I want to throw a custom error and handle it as a separate error and return it using an exception filter.

Please let me know if that can be done.

**Comment by whefter** [comment]
It should be possible to use an exception filter to check if a `BadRequestException` has been thrown (the one in https://github.com/whefter/nestjs-joi/blob/dc0a01476c9bdb6f2f857ef44785ca292abac86d/src/internal/joi.pipe.ts#L128), perhaps check for the beginning of the error message. Let me know if that works for you.

**Comment by VigneshVaidyanathan** [comment]
Yes I am using it like that. I am using an exception filter and tracking if the code is BAD REQUEST with validation error and parsing it. It should be good to allow user to configure how an error is thrown.
Thanks.

**Comment by whefter** [comment]
I'll give some thought to an option to configure the thrown error. But this seems to me to be an edge case that can be covered by the method described above.

**Comment by VigneshVaidyanathan** [comment]
It can be handled using a custom exception filter. Plus do you think you can split the core logic as a `joi-core` and Nest JS modules as separate module? I have forked your repo and I am using the core concept to use decorators to set schema for a type for Angular. Reason I am doing joi validation on angular too is just to make sure both front end and server side does the same validation on the objects. If you have any idea for that, splitting out to a core module, could help reusing that code across different implementations.

**Comment by whefter** [comment]
I added an option for this in v1.3.0, see: https://github.com/whefter/nestjs-joi#pipe-options-pipeopts

If you're in injection-enabled mode, see this for how to pass options to `JoiPipeModule` or to an inline constructor:
* https://github.com/whefter/nestjs-joi#joipipemodule
* https://github.com/whefter/nestjs-joi#defining-pipeopts-in-injection-enabled-mode

Let me know if this works for your use case.

**Comment by whefter** [comment]
Concerning your idea for splitting out the schema generation: it's an idea that I've had myself. Unfortunately I haven't had the time, especially since from what I can see it might involve reconfiguring the project as a monorepo with multiple packages. Though perhaps two separate repos would be best, but that makes testing interdepence somewhat more difficult.

**Comment by VigneshVaidyanathan** [comment]
Looks good. Like the implementation. It can be later extended to get custom exception as input as well.

 I can try to make changes, but I have not contributed to open-source before. Will try to create a PR for that and see next week.

**Comment by VigneshVaidyanathan** [comment]
I do believe making a core module will help. But as you said, it has to be a separate module for core and separate packages for other frameworks. Personally I'm using it in one of my projects to easily perform same validations in both front end and api.

**Comment by whefter** [comment]
Thanks. Closing this issue for now.

**Comment by whefter** [comment]
FYI: I got around to splitting off the core logic into [`joi-class-decorators`](https://www.npmjs.com/package/joi-class-decorators). That should make it easier to use in frontend apps without having to install all the NestJS dependencies.
