### ISSUE TITLE
JoiSchemaOptions stripUnknown and allowUnknown options does not work

### ISSUE THREAD

**Issue by sreeteja06** [whefter/nestjs-joi#5]
```Javascript
import * as Joi from 'joi';
import { JoiSchema, JoiSchemaOptions } from 'nestjs-joi';

@JoiSchemaOptions({ stripUnknown: true, allowUnknown: false })
export class UserDTO {
  @JoiSchema(
    Joi.string()
      .trim()
      .min(10)
      .required(),
  )
  readonly phone: string;
}

```

Version 1.3.1

**Comment by whefter** [comment]
Could you give a more detailed explanation of the issue? What is the expected behavior, what is the actual behavior? Thanks.

**Comment by sreeteja06** [comment]
```Javascript
import * as Joi from 'joi';
import { JoiSchema, JoiSchemaOptions } from 'nestjs-joi';

@JoiSchemaOptions({ stripUnknown: true, allowUnknown: false })
export class CatDTO {
  @JoiSchema(
    Joi.string()
      .trim()
      .required(),
  )
  readonly catName: string;
}
```

This is the DTO, I passed the options allowUnknown false.
The below is the body I am sending 
```JSON
{
    "catName": "here",
    "here": "there"
}
```
**EXPECTED**: Throw a bad request
**ACTUAL**: Allows the body

Below is how I am using the DTO

```Javascript
import { Body, Controller, Post } from '@nestjs/common';
import { CatDTO } from './dto/cat.dto';

@Controller('cat')
export class CatController {
  @Post('/')
  createNewCat(@Body() data: CatDTO): any {
    console.log(data);
    return;
  }
}
```

```Javascript
import { Module } from '@nestjs/common';
import { JoiPipeModule } from 'nestjs-joi';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { CatModule } from './controllers/cat/cat.module';

@Module({
  imports: [CatModule, JoiPipeModule],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**Comment by whefter** [comment]
You are specifying both `stripUnknown` and `allowUnknown`. What's probably happening is that unknown properties are stripped, after which there are no unknown properties. You can try setting `stripUnknown` to `false`, after which it should throw an error.

**Comment by sreeteja06** [comment]
Tried that, still its not throwing an error, and also in both the cases the unknown value is passed down to the controller.
Please find the below attachment for the reference.
![image](https://user-images.githubusercontent.com/28884423/114439008-1f02e980-9be6-11eb-84b4-76e19173593d.png)

**Comment by whefter** [comment]
I tried reproducing the issue, but no luck so far. You can take a look: https://github.com/whefter/nestjs-joi/blob/fix/issue-5-stripUnknown-allowUnknown/test/src/issues/5.spec.ts

How are you including the `JoiPipe`? Via `JoiPipeModule`? Your example didn't show you `app.module.ts`. Could you construct a complete example repo?

**Comment by sreeteja06** [comment]
[https://github.com/sreeteja06/nestjs-joi-test.git](https://github.com/sreeteja06/nestjs-joi-test.git)
Heres a test repo, for you to reproduce the issue.

and the curl  request 
```
curl --location --request POST 'http://localhost:3000/cat' \
--header 'Content-Type: application/json' \
--data-raw '{
    "catName": "example",
    "catPerson": "unknown"
}'
```

**Comment by siavashg87** [comment]
I'm experiencing same issue with allowUnknown: false.

Seems to me like the issue is right here: https://github.com/whefter/nestjs-joi/blob/master/src/internal/joi.pipe.ts#L124

DEFAULT_JOI_OPTS is never overridden by defined options, and here is the last location right before the actual validation by joi.

**Comment by sreeteja06** [comment]
the issue has been resolved, thanks for the update.
