### ISSUE TITLE
Allow unknown false for all fields

### ISSUE THREAD

**Issue by erald14** [whefter/nestjs-joi#8]
IS there any to do 
@JoiSchemaOptions({
    allowUnknown: false,
})
for every class
 without having to append it to every class

**Comment by whefter** [comment]
I've been meaning to implement something that should help with this for a while, take a look at the new `defaultValidationOptions` option for `JoiPipe` in `v1.5.1`: https://github.com/whefter/nestjs-joi#pipe-options-pipeopts

(Don't forget it can be injected when using `JoiPipeModule`).

Going beyond this would require setting global options on the module instance object itself, which is not something I like to do. Let me know if this helps you out.
